### ISSUE TITLE
KeyError: 'template_path'

### ISSUE THREAD

**Issue by ericsfraga** [ahrenberg/nbcorg#3]
Hello,

I have just tried this package, something which will be quite useful, but I'm getting the following error when I try to use it:
```
jupyter nbconvert SSVsCode.ipynb --to orgmode
[NbConvertApp] Converting notebook SSVsCode.ipynb to orgmode
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'template_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/jupyter-nbconvert", line 33, in <module>
    sys.exit(load_entry_point('nbconvert==5.6.1', 'console_scripts', 'jupyter-nbconvert')())
[...]
```
Any advice would be welcome! Thank you.

**Comment by ahrenberg** [comment]
Thanks! Will try to have a look at it. I believe nbconvert was overhauled a while back, and I did not keep up with nbcorg development. I'll try to make the plugin work with the new version of nbconvert. At the moment not sure how much effort, but hopefully the docs have been updated as well by now.
